language: node_js
node_js:
  - "node"

cache: yarn

before_install:
  - sudo apt-get install lftp

script:
  - yarn docs:build

after_script:
  - lftp -c "set ftp:ssl-allow no; open -u $FTP_USER,$FTP_PASSWORD ftp://$FTP_HOST/docs; mirror -eRv ./docs/.vuepress/dist .; quit;"

